### ISSUE TITLE
image / file type recognition

### ISSUE THREAD

**Issue by superflausch** [aelvan/FocalPointField-Craft#2]
First, thanks for an amazing plugin. This is so much nicer then selecting the crop position out of a dropdown menu.

I found a small issue. It looks like you (or Craft) checks the file type to determine if the asset is an actual image. I have tested it with a couple of images and it looks like that only lowercase file extensions get recognised. So an image with the name myimage.JPG won't work and I get the message "This is not an image". Simply changing it to myimage.jpg works as expected.

Cheers.

**Comment by aelvan** [comment]
Right, that was fixed yesterday, try updating the plugin and let me know if that helps.

**Comment by superflausch** [comment]
I just noticed that you made another commit. After the update it's working as expected.

Sorry about that.
