### ISSUE TITLE
Clear transform cache after image is replaced

### ISSUE THREAD

**Issue by wbrowar** [aelvan/FocalPointField-Craft#3]
I don't know if this is something you can fix, but I noticed that when I replaced an image in Assets, the image doesn't update in the Focal Point field. When I cleared the cache it was then updated.

**Comment by aelvan** [comment]
I tried to recreate this, but wasn't able to. The steps I tried was:

1) Upload a file.
2) Double-clicked the image to bring up the modal.
3) Set a focal point and clicks "Save".
4) Selects the image, and choose "Replace file" from the tool dropdown.
5) Double click on the image to bring up the modal again.

And the new image is in the focal point field. 

What did I do wrong? :)
