### ISSUE TITLE
Syntax for Using FocalPointField

### ISSUE THREAD

**Issue by marflow** [aelvan/FocalPointField-Craft#6]
Hello André,
Thanks a lot for developing and sharing imager/focalPoint as free plugins! The combination would be very handy for me but I´m having trouble finding the right spot and syntax for the FocalPointField. I tried my "... position: 'my-fpf-fieldname', but if I put it there once I get errors, and included twice it is ignored. (Entering % values works.) Sorry if I miss something obvious!
Wolfram

**Comment by aelvan** [comment]
Hi, 

If you have an asset with this field on, you'd access it with `myAsset.fieldName`. And inside a twig object, that'd be `position: myAsset.fieldName`.

Let me know if that helped.

**Comment by marflow** [comment]
It´s working wonderfully now! ( I have it inside a twig object and but only had tried inside {...} or inside '...' .) Thank you so much for your instant reply and help!
